import prisma from './src/utils/prismaClient';

const EMAIL   = 'connect@miniguru.in';
const COMPANY = 'MiniGuru Innovation Private Limited';
const ADDRESS = 'Ujjain, Madhya Pradesh, India';
const WEBSITE = 'https://miniguru.in';
const DATE    = 'June 1, 2026';

const privacy = { title: 'Privacy Policy', lastUpdated: DATE, sections: [
  { heading: '1. About Us', body: `${COMPANY} ("MiniGuru", "we", "us") operates the MiniGuru platform at ${WEBSITE}. We provide STEAM (Science, Technology, Engineering, Art, and Mathematics) education services for children aged 8–14 in India. Registered office: ${ADDRESS}.` },
  { heading: '2. Who Uses MiniGuru', body: `MiniGuru has two types of users:\n\n**Primary Users — Children (aged 8–14):** Children are the core users of MiniGuru. They browse projects, plan and build STEAM projects, upload project videos, and participate in the community.\n\n**Secondary Users — Parents, Guardians, Schools, and T-LAB Coordinators:** These are adults who register on behalf of children or manage child accounts. Parents and guardians oversee their child's activity. Schools and T-LAB coordinators manage student accounts in bulk and track class progress.` },
  { heading: '3. Information We Collect', body: `**Child Accounts:** First name, last name, age, and the parent or guardian's email address (for OTP verification and communications). Login ID is auto-generated as firstname.lastname@miniguru.in.\n\n**Parent / Guardian Accounts:** Real name, email address, and optional phone number.\n\n**School / T-LAB Accounts:** Institution name, coordinator name, email, and optional phone.\n\n**Project Content:** Project title, description, category, materials selected, project dates, and video recording.\n\n**Usage Data:** Pages visited, videos watched, Goins earned, project history.\n\n**Device Info:** Browser type, operating system, IP address (for security and performance).\n\n**Communications:** Emails sent to ${EMAIL} are retained to resolve your query.` },
  { heading: '4. How We Use Your Information', body: `To create and manage accounts; operate the Goins motivation system; review and approve child project videos before publication; send transactional emails (OTP verification, password reset, project approvals) via SendGrid; send project material kit lists to parent emails; improve the platform; ensure child safety; respond to support requests; comply with our legal obligations.` },
  { heading: '5. Children\'s Privacy — DPDPA 2023 & POCSO', body: `**Parental Consent:** A one-time password (OTP) is sent to the parent or guardian's email before any child account is created. No child account is created without verified guardian consent.\n\n**Data Minimisation:** We collect only what is necessary. Children are not required to provide a phone number, home address, or financial information.\n\n**No Advertising:** We never show advertisements to children and never use children's data for behavioural profiling.\n\n**No Sale of Data:** We never sell, rent, or trade any user data to any third party.\n\n**Video Review:** All child-submitted videos are held as UNLISTED on YouTube until reviewed and approved by our team. Videos not meeting our guidelines are rejected and not published.\n\n**POCSO Compliance:** Any content violating the Protection of Children from Sexual Offences Act, 2012 will be immediately removed and reported to the relevant authorities.\n\n**Right to Delete:** Parents or guardians may request deletion of their child's account and all associated data at any time by emailing ${EMAIL}. We process requests within 30 days.` },
  { heading: '6. Amazon Affiliate Disclosure', body: `MiniGuru participates in the Amazon Associates Programme (affiliate tag: miniguru08-21). When a child selects project materials, we display curated Amazon.in links for purchasing those materials. If a purchase is made through our link, MiniGuru may earn a small affiliate commission (4–6%) at no extra cost to the buyer. We only include materials that are genuinely relevant to STEAM projects. Our materials selection is not influenced by commission rates.` },
  { heading: '7. Third-Party Services', body: `We use the following trusted third-party services to operate MiniGuru:\n\n• Google / YouTube — Video hosting\n• Firebase (Google) — App hosting and image storage\n• MongoDB Atlas — Cloud database\n• SendGrid (Twilio) — Transactional email\n• Amazon Associates — Affiliate material links\n\nEach provider has their own privacy policy. We share only the minimum necessary data with each.` },
  { heading: '8. Data Storage & Security', body: `Data is stored in India (Google Cloud asia-south1, Mumbai) and the United States (MongoDB Atlas). We implement HTTPS/TLS encryption, bcrypt password hashing, JWT-based authentication, and role-based access control. We do not store payment card details. If you believe your account has been compromised, contact ${EMAIL} immediately.` },
  { heading: '9. Your Rights Under DPDPA 2023', body: `You have the right to access your personal data; correct inaccurate data; request erasure; raise a grievance with our Grievance Officer; designate a nominee.\n\nTo exercise these rights, email ${EMAIL} with subject line "Data Rights Request". We respond within 30 days.` },
  { heading: '10. Grievance Officer', body: `Name: Pramod Maithil\nDesignation: Founder & Director\nCompany: ${COMPANY}\nAddress: ${ADDRESS}\nEmail: ${EMAIL}\n\nComplaints acknowledged within 48 hours, resolved within 30 days.` },
  { heading: '11. Changes to This Policy', body: `We may update this policy periodically. We will notify registered users by email and update the "Last Updated" date. Continued use of MiniGuru after changes are posted constitutes acceptance of the updated policy.` },
  { heading: '12. Contact Us', body: `${COMPANY}\n${ADDRESS}\nEmail: ${EMAIL}\nWebsite: ${WEBSITE}` }
]};

const terms = { title: 'Terms & Conditions', lastUpdated: DATE, sections: [
  { heading: '1. Acceptance of Terms', body: `These Terms and Conditions govern your use of the MiniGuru platform operated by ${COMPANY}. By using MiniGuru, you agree to these Terms. If you are a parent, guardian, or school registering on behalf of children, you accept these Terms on their behalf.` },
  { heading: '2. Who Can Use MiniGuru', body: `**Primary Users — Children (aged 8–14):** Children are the main users of MiniGuru. They plan and build STEAM projects, upload project videos, earn Goins, and participate in the community.\n\n**Secondary Users — Parents and Guardians:** Adults who register children and oversee their activity. Parents receive project material lists by email and manage password recovery for their children.\n\n**Secondary Users — Schools and T-LAB Coordinators:** Educational institutions that register student accounts in bulk and monitor class-level activity.\n\nChildren under 18 must have a parent or guardian's consent to register. By creating a child account, the parent or guardian confirms they have read and accepted these Terms.` },
  { heading: '3. Account Registration', body: `**Child Accounts:** A unique MiniGuru ID is generated as firstname.lastname@miniguru.in. A one-time password (OTP) is sent to the parent's email to verify consent before the account is created.\n\n**Parent / Guardian Accounts:** Register with a real email address. Multiple children can be added under one parent account.\n\n**School / T-LAB Accounts:** Bulk registration is available. Credentials are generated and provided to the school coordinator for distribution to students.\n\nYou are responsible for keeping login credentials confidential. Report any unauthorised access immediately to ${EMAIL}.` },
  { heading: '4. The Goins Motivation System', body: `Goins are MiniGuru's virtual reward system designed to boost motivation and encourage creative consistency.\n\n• Children earn Goins by completing and submitting projects, receiving community engagement (likes and comments), and maintaining consistent participation.\n• Goins are a measure of a child's creative journey — the more they build, the more they earn.\n• Goins do not purchase materials. Materials are purchased by parents through Amazon using the kit link sent to their email.\n• Goins have absolutely no real monetary value. They cannot be exchanged for cash, transferred between users, or used outside MiniGuru.\n• MiniGuru reserves the right to adjust the Goins system at any time.\n• Any attempt to exploit or manipulate the Goins system will result in immediate account suspension.` },
  { heading: '5. User-Generated Content — Project Videos', body: `By submitting a project video, you grant MiniGuru a non-exclusive, royalty-free, worldwide licence to host and display that video on our platform and YouTube channel (@MiniGuru.innovation).\n\nAll submitted videos are reviewed by our team before publication. We reserve the right to reject any video without obligation to provide reasons, though we will notify the submitter.\n\nProhibited content includes anything violent, sexual, hateful, discriminatory, or illegal. Content violating POCSO will be reported to authorities. Repeated violations result in permanent account termination.\n\nParents may request removal of their child's video at any time by emailing ${EMAIL}.` },
  { heading: '6. Shop & Amazon Affiliate Links', body: `MiniGuru currently displays curated STEAM project materials with links to purchase them on Amazon.in through our Associates programme (tag: miniguru08-21).\n\nMiniGuru does not process any payments. All purchases are completed directly on Amazon.in and are subject to Amazon's own terms of service, return policy, and privacy policy. MiniGuru is not responsible for any transaction made on Amazon.\n\nMiniGuru's own curated store for project kits is coming soon. When available, purchases will be processed through a secure payment gateway. MiniGuru will not store payment card details.` },
  { heading: '7. T-LAB & Consultancy Services', body: `MiniGuru offers T-LAB setup consultancy and workshop services for schools and institutions. These services are governed by separate agreements. The platform terms do not constitute a binding service agreement for institutional engagements. For T-LAB inquiries, contact ${EMAIL}.` },
  { heading: '8. Intellectual Property', body: `All MiniGuru platform content — logo, design, graphics, text, and software — is the intellectual property of ${COMPANY} protected under applicable Indian law. You may not reproduce or distribute our content without prior written permission.\n\nUser-generated content (project videos and descriptions) remains the intellectual property of the child who created it. Uploading content grants us the licence described in Section 5.` },
  { heading: '9. Prohibited Conduct', body: `You must not: provide false registration information; impersonate others; access other users' accounts; upload harmful or illegal content; use bots or scrapers; reverse-engineer MiniGuru systems; manipulate the Goins system; use MiniGuru for unauthorised commercial purposes.` },
  { heading: '10. Limitation of Liability', body: `MiniGuru is provided "as is". To the maximum extent permitted by Indian law, ${COMPANY} is not liable for indirect or consequential damages including loss of Goins, project data, or platform downtime. MiniGuru is an educational platform and does not guarantee specific learning outcomes.` },
  { heading: '11. Governing Law', body: `These Terms are governed by Indian law. Disputes are subject to the exclusive jurisdiction of courts in Ujjain, Madhya Pradesh. We encourage users to first contact us at ${EMAIL} to resolve issues amicably.` },
  { heading: '12. Changes to Terms', body: `We may update these Terms periodically. We will notify users by email and update the "Last Updated" date. Continued use of the platform constitutes acceptance of revised Terms.` },
  { heading: '13. Contact', body: `${COMPANY}\n${ADDRESS}\nEmail: ${EMAIL}\nWebsite: ${WEBSITE}` }
]};

const cookie = { title: 'Cookie Policy', lastUpdated: DATE, sections: [
  { heading: '1. What We Use', body: `MiniGuru uses only essential cookies:\n\n• Authentication Token — keeps you logged in for up to 7 days. Essential for the platform to function. Cleared when you log out.\n• Session Preferences — stores lightweight UI preferences locally in your browser. No personal data is sent to our servers.\n\nWe do not use advertising, tracking, or third-party analytics cookies.` },
  { heading: '2. Third-Party Cookies', body: `Project videos are embedded from YouTube, which may set its own cookies per Google's Cookie Policy. We use privacy-enhanced YouTube embeds where possible to minimise third-party cookie use.` },
  { heading: '3. Managing Cookies', body: `You can manage cookies through your browser settings. Blocking essential cookies will prevent you from logging in. Since we don't use non-essential cookies, no opt-out is needed.` },
  { heading: '4. Contact', body: `For cookie-related questions: ${EMAIL}` }
]};

const faq = { sections: [
  { title: 'For Parents & Guardians', items: [
    { q: 'What is MiniGuru?', a: 'MiniGuru is a STEAM (Science, Technology, Engineering, Art, Mathematics) education platform for Indian children aged 8–14. Children plan real hands-on projects, build them at home or in a T-LAB, record a short video, and share it with our community. They earn Goins — virtual rewards that celebrate their creative consistency — as they build more projects.' },
    { q: 'Is MiniGuru safe for my child?', a: 'Yes. Child safety is our top priority. We comply with India\'s DPDPA 2023 and POCSO guidelines. A parent OTP is required before any child account is created. All child-submitted videos are reviewed by our team before being made visible to anyone. We never show advertisements to children and never sell user data.' },
    { q: 'What is the MiniGuru ID?', a: 'Each child gets a unique login ID automatically generated as firstname.lastname@miniguru.in (e.g. aarav.sharma@miniguru.in). This is not a real email address — it is only a login ID. All communications and OTPs go to the parent\'s real email provided during registration.' },
    { q: 'What are Goins?', a: 'Goins are MiniGuru\'s virtual reward system. They are designed to boost motivation and encourage children to keep building and creating consistently. Children earn Goins by completing projects, receiving likes, and engaging with the community. Goins celebrate a child\'s creative journey — the more they build, the more they earn. Goins have no monetary value and are not used to purchase materials.' },
    { q: 'How do children get project materials?', a: 'When a child plans a project, MiniGuru shows a curated list of materials needed. The child selects what they need, and the app sends you (the parent) an email with the complete list and a single "Buy on Amazon" link. That link opens an Amazon cart pre-loaded with all the items — you just review and check out. No browsing needed.' },
    { q: 'What happens after my child submits a video?', a: 'The video is held UNLISTED on YouTube — not publicly searchable. Our team reviews it within 48 hours. If approved, it becomes visible on MiniGuru and the child earns Goins. If not approved, we notify the child with a reason so they can try again.' },
    { q: 'How do I delete my child\'s account?', a: 'Email connect@miniguru.in with your child\'s MiniGuru ID and a request to delete. We delete the account and all associated data within 30 days. If you also want their videos removed from YouTube, please mention that specifically.' },
    { q: 'How do I reset my child\'s password?', a: 'Tap "Forgot Password" on the login screen and enter your child\'s MiniGuru ID. A password reset link is sent to the parent email registered for that account. If you no longer have access to that email, contact connect@miniguru.in.' }
  ]},
  { title: 'For Schools & T-LABs', items: [
    { q: 'What is a T-LAB?', a: 'A T-LAB (Tinkering Lab) is a dedicated hands-on STEAM workspace in a school. MiniGuru partners with schools to set up T-LABs and provides curriculum support, project ideas, material guidance, and the MiniGuru platform for documentation and community sharing.' },
    { q: 'How do we register students in bulk?', a: 'School accounts have a bulk registration feature. Enter student names or paste from a spreadsheet — the system generates MiniGuru IDs and initial passwords for all students instantly. A credentials sheet can be downloaded or emailed directly to the teacher.' },
    { q: 'How do we set up a T-LAB in our school?', a: 'Visit the Consultancy section in the MiniGuru app or contact us at connect@miniguru.in. Our team will guide you through space requirements, equipment, curriculum integration, and partnership options.' }
  ]},
  { title: 'About Goins', items: [
    { q: 'How do children earn Goins?', a: 'Children earn Goins for being creative and consistent: 100 Goins on account creation, +50 Goins when a project video is approved, +5 Goins when another user likes their video, +10 Goins when someone comments on their video. The more they build, the more they earn.' },
    { q: 'What are Goins used for?', a: 'Goins are a motivation and consistency tracker. They celebrate the child\'s creative journey and encourage them to keep building. A child\'s Goins balance shows how active and creative they are on the platform. Goins are not used to purchase materials — materials are bought by parents through Amazon.' },
    { q: 'Do Goins expire?', a: 'No, Goins do not expire while the account is active. They are forfeited only if the account is deleted.' }
  ]},
  { title: 'Technical Help', items: [
    { q: 'The app is not loading.', a: 'Try refreshing the page or clearing your browser cache. MiniGuru works best on Chrome, Edge, or Safari. If the problem persists, contact connect@miniguru.in.' },
    { q: 'My child\'s video upload failed.', a: 'Ensure the file is under 500MB and under 5 minutes long. Check your internet connection and try again. If the problem continues, email connect@miniguru.in with your child\'s MiniGuru ID.' },
    { q: 'I cannot log in.', a: 'Enter your full MiniGuru ID (e.g. aarav.sharma@miniguru.in) and correct password. Use "Forgot Password" to reset. Still stuck? Email connect@miniguru.in.' }
  ]}
]};

async function main() {
  const updates = [
    { key: 'legal_privacy', value: privacy as any },
    { key: 'legal_terms',   value: terms   as any },
    { key: 'legal_cookie',  value: cookie  as any },
    { key: 'faq',           value: faq     as any },
  ];
  for (const u of updates) {
    await prisma.siteContent.upsert({
      where:  { key: u.key },
      update: { value: u.value },
      create: { key: u.key, value: u.value },
    });
    console.log(`✅ ${u.key} updated`);
  }
  console.log('\n✅ All legal content updated successfully.');
  await prisma.$disconnect();
}
main().catch(e => { console.error(e); process.exit(1); });
